version: "3"

services:

  db:
    image: mysql:8.1.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 02122004
      MYSQL_DATABASE: rip_db
      MYSQL_PASSWORD: 02122004
    ports:
      - "3306:3306"

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server-builder
    container_name: server_container
    ports:
      - "8000:8000"
      - "8080:8080"

  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: client-builder
    container_name: client_container
    ports:
      - "3000:3000"
